export const routes = {
  home: "/",
  about: "/about",
  pricing: "/pricing",
  blog: "/blog",
  faq: "/faq",
  contact: "/contact",
  terms: "/terms",
  privacy: "/privacy",
  cookies: "/cookies",
  help: "/help",
  support: "/support",

  login: "/login",
  register: "/register",
  otp: "/otp",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",

  dashboard: "/dashboard",
  astrology: "/dashboard/astrology",
  matrimony: "/dashboard/matrimony",
  onboarding: "/dashboard/onboarding",
  profile: "/dashboard/profile",
  editProfile: "/dashboard/profile/edit",
  preferences: "/dashboard/preferences",
  birthDetails: "/dashboard/birth-details",

  kundli: "/dashboard/kundli",
  chartNorth: "/dashboard/kundli/north",
  chartSouth: "/dashboard/kundli/south",
  chartEast: "/dashboard/kundli/east",
  planets: "/dashboard/kundli/planets",
  nakshatra: "/dashboard/kundli/nakshatra",
  dasha: "/dashboard/kundli/dasha",
  transit: "/dashboard/kundli/transit",
  gochar: "/dashboard/kundli/gochar",
  /** Yogas & doshas detail view (implemented on the transit extras page). */
  yogas: "/dashboard/kundli/transit",
  rajaYogas: "/dashboard/kundli/raja-yogas",
  natalProfile: "/dashboard/kundli/natal-profile",
  divisionalCharts: "/dashboard/kundli/charts",
  ashtakavarga: "/dashboard/kundli/ashtakavarga",
  remedies: "/dashboard/remedies",
  lalKitab: "/dashboard/remedies",
  predictions: "/dashboard/predictions",
  marriageTiming: "/dashboard/kundli/marriage-timing",
  horoscope: "/dashboard/horoscope",

  compatibility: "/dashboard/compatibility",
  compatibilityReport: "/dashboard/compatibility/report",
  aiInsights: "/dashboard/ai-insights",
  vedicWisdom: "/dashboard/vedic-wisdom",
  wisdomJournal: "/dashboard/vedic-wisdom/journal",
  askTheSages: "/dashboard/vedic-wisdom/ask-the-sages",
  wisdomVoice: "/dashboard/vedic-wisdom", // append `/${guideId}/voice`
  recommendations: "/dashboard/recommendations",

  search: "/dashboard/search",
  filters: "/dashboard/search/filters",
  matches: "/dashboard/matches",
  matchCompare: "/dashboard/matches/compare",
  matchProfile: "/dashboard/matches/profile",
  visitors: "/dashboard/visitors",
  likes: "/dashboard/likes",
  shortlisted: "/dashboard/shortlisted",
  connections: "/dashboard/connections",
  yourConnection: "/dashboard/your-connection",

  messages: "/dashboard/messages",
  chat: "/dashboard/chat",
  chatVideo: "/dashboard/chat/video",
  notifications: "/dashboard/notifications",

  premium: "/dashboard/premium",
  payments: "/dashboard/billing",
  checkout: "/dashboard/billing/checkout",
  paymentSuccess: "/dashboard/billing/success",
  paymentFailure: "/dashboard/billing/failure",
  invoice: "/dashboard/billing/invoice",
  invoices: "/dashboard/billing/invoices",
  downloads: "/dashboard/downloads",
  reports: "/dashboard/reports",

  consultation: "/dashboard/consultation",
  bookConsultation: "/dashboard/consultation/book",
  astrologer: "/dashboard/consultation/astrologer",
  calendar: "/dashboard/calendar",

  settings: "/dashboard/settings",
  security: "/dashboard/settings/security",
  privacySettings: "/dashboard/settings/privacy",
  appearance: "/dashboard/settings/appearance",
  languageRegion: "/dashboard/settings/language",
  blocked: "/dashboard/settings/blocked",

  admin: "/admin",
  adminUsers: "/admin/users",
  adminReports: "/admin/reports",
  adminPayments: "/admin/payments",
  adminAi: "/admin/ai",
  adminAnalytics: "/admin/analytics",
  adminCms: "/admin/cms",

  maintenance: "/maintenance",
  health: "/api/health",
} as const;

export type AppRoute = (typeof routes)[keyof typeof routes];

/** Consultation virtual-astrologer deep links */
export const consultationPaths = {
  astrologer: (id: string) => `${routes.consultation}/${id}`,
  chat: (id: string) => `${routes.consultation}/${id}/chat`,
  voice: (id: string) => `${routes.consultation}/${id}/voice`,
} as const;
